// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_QGaxpn5J8p70_xpSNQgxsXz9C3E4bI',
    appId: '1:1051041039104:web:52534541bee78be7a529e5',
    messagingSenderId: '1051041039104',
    projectId: 'tiktok-tiktok-clone',
    authDomain: 'tiktok-tiktok-clone.firebaseapp.com',
    databaseURL: 'https://tiktok-tiktok-clone-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiktok-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL1DmHdqobW4LG6IUn_2xnVC42-2CLmys',
    appId: '1:1051041039104:android:ef8a41b3922db13ca529e5',
    messagingSenderId: '1051041039104',
    projectId: 'tiktok-tiktok-clone',
    databaseURL: 'https://tiktok-tiktok-clone-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiktok-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJb18JwIDzNKrzKt5VdJ2X-9Ipa4VXahE',
    appId: '1:1051041039104:ios:7907937d4097b5aaa529e5',
    messagingSenderId: '1051041039104',
    projectId: 'tiktok-tiktok-clone',
    databaseURL: 'https://tiktok-tiktok-clone-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiktok-tiktok-clone.appspot.com',
    iosBundleId: 'co.flutter.tiktokclone',
  );
}
